/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Leap__Motion_WRAP_H_
#define SWIG_Leap__Motion_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_Listener : public Leap::Listener, public Swig::Director {

public:
    SwigDirector_Listener(VALUE self);
    virtual ~SwigDirector_Listener();
    virtual void onInit(Leap::Controller const &arg0);
    virtual void onConnect(Leap::Controller const &arg0);
    virtual void onDisconnect(Leap::Controller const &arg0);
    virtual void onExit(Leap::Controller const &arg0);
    virtual void onFrame(Leap::Controller const &arg0);
    virtual void onFocusGained(Leap::Controller const &arg0);
    virtual void onFocusLost(Leap::Controller const &arg0);
};


#endif
